AirlinesReservation/Models/Emloyee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emloyee
    {
        public int Employee_id { get; set; }
        public string Full_name { get; set; }
        public string Img { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Address { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Roles { get; set; }
    }
}

AirlinesReservation/Controllers/EmloyeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirlinesReservation.Models;

namespace AirlinesReservation.Controllers
{
    public class EmloyeesController : Controller
    {
        private DB_AirlinesReservationEntities db = new DB_AirlinesReservationEntities();

        // GET: Emloyee
        public ActionResult Index()
        {
            ViewBag.Emloyee = db.Emloyee.ToList();
            return View();
        }

        
        // GET: Emloyee/Create
        public ActionResult _Create()
        {
            return PartialView("_Create");
        }
        public ActionResult Logout(int id)
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "Home", new { id = 1 });
        }
        // POST: Emloyee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Create([Bind(Include = "Employee_id,Full_name,Img,Email,Age,Sex,Address,User_name,Password,Roles")] Emloyee emloyee)
        {
            Random random = new Random();
            string _FileName = "";
            string _path = "";
            emloyee.Employee_id = random.Next();
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["image"];            
                if (file.FileName != "")
                {
                    string name = file.FileName;
                    string tail = name.Substring(name.IndexOf("."));
                    _FileName = emloyee.Employee_id + tail;
                    _path = Path.Combine(Server.MapPath("~/img"), _FileName);
                    file.SaveAs(_path);
                }
                else
                {
                    _FileName = "default.jpg";
                }
                
                emloyee.Img = _FileName;
                emloyee.Roles = 0;
                db.Emloyee.Add(emloyee);
                String mes = "Account creation failed!!! Account already exists";
                if (checkexist(emloyee.User_name) == null)
                {
                    db.SaveChanges();
                    delete();
                    mes = "Create Account Success";
                }
                TempData["mes"] = "<script>alert('"+mes+"');</script>";
            }
            delete();
            return RedirectToAction("Index");
        }
        private Emloyee checkexist(String username)
        {
            Emloyee em = db.Emloyee.Where(e => e.User_name==username).FirstOrDefault();
            return em;
        }
        private void delete()
        {
          
            int h = db.Emloyee.Count(n => n.Full_name == null);
            for (int i = 0; i < h; i++)
            {
                Emloyee id = db.Emloyee.Where(x => x.Full_name == null).FirstOrDefault();
                db.Emloyee.Remove(id);
                db.SaveChanges();
            }
        }
        // GET: Emloyee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Emloyee emloyee = db.Emloyee.Find(id);
            if (emloyee == null)
            {
                return HttpNotFound();
            }
            return View(emloyee);
        }
        
        // POST: Emloyee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Employee_id,Full_name,Img,Email,Age,Sex,Address,User_name,Password,Roles")] Emloyee emloyee)
        {
            string _FileName = "";
            string _path = "";
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["image"];
                if (file.FileName != "")
                {
                    string name = file.FileName;
                    string tail = name.Substring(name.IndexOf("."));
                    _FileName = emloyee.Employee_id + tail;
                    _path = Path.Combine(Server.MapPath("~/img"), _FileName);
                    file.SaveAs(_path);
                }
                else
                {
                    _FileName = emloyee.Img;
                }
                emloyee.Img = _FileName;
                db.Entry(emloyee).State = EntityState.Modified;
                db.SaveChanges();
                String mes = "Successfully updated";
                TempData["mes"] = "<script>alert('" + mes + "');</script>";
                return RedirectToAction("Index");
            }
            return View(emloyee);
        }

        // GET: Emloyee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
         
            Emloyee emloyee = db.Emloyee.Find(id);
            ViewBag.Emloyee = emloyee;
            if (emloyee == null)
            {
                return HttpNotFound();
            }
            return View(emloyee);
        }

        // POST: Emloyee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Emloyee emloyee = db.Emloyee.Find(id);
            db.Emloyee.Remove(emloyee);
            db.SaveChanges();
            String mes = "Successfully Delete";
            TempData["mes"] = "<script>alert('" + mes + "');</script>";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

AirlinesReservation/Views/Emloyees/Delete.cshtml
@model AirlinesReservation.Models.Emloyee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_myLayout.cshtml";


}
<div class="container-fluid">
    <div class="row page-titles">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="~/admin/index">Admin</a></li>
            <li class="breadcrumb-item"><a href="">Manage Account</a></li>
        </ol>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body text-center">

                @{ string linkimg = "/img/default.jpg";
                    if (ViewBag.Emloyees.Img != "")
                    {
                        linkimg = "/img/" + ViewBag.Emloyees.Img;
                    }
                    string name = ViewBag.Emloyees.Full_name;
                    string address = ViewBag.Emloyees.Address;
                    int Age = ViewBag.Emloyees.Age;
                    string Email = ViewBag.Emloyees.Email;
                    int sex = ViewBag.Emloyees.Sex;
                    string Sexemloyee = "";
                    switch (sex)
                    {
                        case 0:
                            Sexemloyee = "Nam";
                            break;
                        case 1:
                            Sexemloyee = "Nữ";
                            break;
                    }
                    string Addres = ViewBag.Emloyees.Address;
                }
                <img src="@linkimg" alt="avatar" class="rounded-circle img-fluid" style="width: 250px;">
                <h1 class="" style="font-family:'Times New Roman'">@name</h1>
                <div class="container" style="text-align:left">
                    <h2 class="">Address: @address</h2>
                    <h2 class="">Email: @Email</h2>
                    <h2 class="">Age: @Age</h2>
                    <h2 class="">Sex: @Sexemloyee</h2>
                    <div class="table-responsive">
                        <h1>Are you sure you want to delete this?</h1>
                        <div>
                            <h1>Emloyee</h1>
                            <hr />
                            <dl class="dl-horizontal" style="display:none;">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Full_name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Full_name)
                                </dd>
                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <div class="col-md-offset-2 col-md-12 d-flex justify-content-between">
                                        <div>
                                            <a href="/Emloyees/Index" class="btn btn-rounded btn-outline-secondary">Back</a>
                                        </div>
                                        <input type="submit" value="Delete" class="btn btn-rounded btn-success" />
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AirlinesReservation/Views/Emloyees/Edit.cshtml
@model AirlinesReservation.Models.Emloyee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}
    <div class="container-fluid">
            <div class="row page-titles">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item">Manage Account<a href="/Admin/Index"></a></li>
                    <li class="breadcrumb-item"><a href="/Emloyees/Index">Account</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Update Account</li>
                </ol>
            </div>
            <div class="row">
                <div class="col-12 h-75">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="container-fluid">
                               
                                @using (Html.BeginForm("Edit", "Emloyees", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()
                                    var img = "/img/" + Model.Img;
                                <div class="form-horizontal center" style="color:black;font-size:1.5em;">
                                    <h1>Emloyee</h1>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger " })
                                    @Html.HiddenFor(model => model.Employee_id)
                                   
                                    <div class="form-group">
                                        
                                        <img src="@img" id="image" height="150" width="150" /> <br />
                                        <input type="file" name="image" id="file" class="inputfile" />
                                        <label for="file">Choose a file</label>
                                        @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Full_name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.Full_name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Full_name, "", new { @class = "text-danger" })
                                    </div>



                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "mb-1" })
                                        @Html.DropDownListFor(model => model.Sex, new List<SelectListItem> { new SelectListItem { Text = "Nam", Value = "0" }, new SelectListItem { Text = "Nữ", Value = "1" } }, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.User_name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.User_name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.User_name, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group" style="display:none;">
                                        @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
                                        @Html.DropDownListFor(model => model.Roles, new List<SelectListItem> { new SelectListItem { Text = "Nhân viên", Value = "0" }, new SelectListItem { Text = "Adnin", Value = "1" } }, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group" style="margin-top:1.5em;">
                                        <div class="col-md-offset-2 col-md-12 d-flex justify-content-between">
                                            <div>
                                                <a href="/Emloyees/Index" class="btn btn-rounded btn-outline-secondary">Back</a>
                                            </div>
                                            <input type="submit" value="Save" class="btn btn-rounded btn-success" />
                                        </div>
                                    </div>
                                </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

AirlinesReservation/Views/Emloyees/Index.cshtml
@{
    ViewBag.Title = "Manage Emloyee";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}
@Html.Raw(TempData["mes"])
<div class="container-fluid">
    <div class="row page-titles">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="~/admin/index">Admin</a></li>
            <li class="breadcrumb-item"><a href="">Manage Flights</a></li>
        </ol>
    </div>
    <div class="card-header d-flex justify-content-between">
        <div> <h4 class="card-title">Manage Emloyee</h4></div>>
        <button type="button" class="btn btn-rounded btn-success pull-right" data-bs-toggle="modal" data-bs-target=".bd-example-modal-lg">
            <span class="btn-icon-start text-info">
                <i class="fa fa-plus color-info"></i>
            </span>Add
        </button>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example3" class="display" style="min-width: 845px">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Employee id</th>
                                <th>Full name</th>
                                <th>User name</th>
                                <th>Password</th>
                                <th>Email</th>
                                <th>Age</th>
                                <th>Sex</th>
                                <th>Address</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var em in ViewBag.Emloyee)
                            {
                                if (em.Roles != 1)
                                {
                                    <tr>
                                        @{
                                            string linkimg = "/img/default.jpg";
                                            if (@em.Img != "")
                                            {

                                                linkimg = "/img/" + @em.Img;
                                            }
                                            string Sex = "";
                                            switch (@em.Sex)
                                            {
                                                case 0:
                                                    Sex = "Nam";
                                                    break;
                                                case 1:
                                                    Sex = "Nữ";
                                                    break;
                                            }

                                        }
                                        <td><img class="rounded-circle" width="50" height="50" src="@linkimg" alt=""></td>
                                        <td>@em.Employee_id</td>
                                        <td>@em.Full_name</td>
                                        <td>@em.User_name</td>
                                        <td>@em.User_name</td>
                                        <td>@em.Email</td>
                                        <td>@em.Age</td>
                                        <td>Sex</td>
                                        <td>@em.Address</td>
                                        <td>
                                            <div class="d-flex">
                                                @Html.ActionLink("Edit", "Edit", new { id = em.Employee_id }, new { @class = "btn btn-primary shadow btn-xs sharp me-1 fas fa-pencil-alt" })
                                                @Html.ActionLink("Delete", "Delete", new { id = em.Employee_id }, new { @class = "btn btn-primary shadow btn-xs sharp me-1 fa fa-trash" })
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

AirlinesReservation/Views/Emloyees/_Create.cshtml
@model AirlinesReservation.Models.Emloyee
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"> Emloyee</h4>
                
                <button type="button" class="btn-close" data-bs-dismiss="modal">
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("_Create", "Emloyees", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                            @Html.LabelFor(model => model.Full_name, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Full_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Full_name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "mb-1" })
                        <input type="file" name="image" class="form-control" />
                        @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                    </div>

                    

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                            @Html.LabelFor(model => model.User_name, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.User_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.User_name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="mb-3" style="margin-top:1.5em;">
                        <input type="submit" value="Create" class="btn btn-primary btn-block" />
                    </div>
                </div>
                }
            </div>
            <div class="modal-footer">
                
            </div>
        </div>
    </div>
</div>