AirlinesReservation/Models/Discount.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public string Discount_id { get; set; }
        public Nullable<int> Flight_id { get; set; }
        public Nullable<int> Discount1 { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}

AirlinesReservation/Controllers/DiscountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirlinesReservation.Models;

namespace AirlinesReservation.Controllers
{ 
    public class DiscountsController : Controller
    {
        private DB_AirlinesReservationEntities db = new DB_AirlinesReservationEntities();

        // GET: Discount
        public ActionResult Index()
        {
            var Discount = db.Discount.Include(d => d.Flight);
            return View(Discount.ToList());
        }

        // GET: Discount/Details/5
        public ActionResult Logout(int id)
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "Home", new { id = 1 });
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discount discount = db.Discount.Find(id);
            if (discount == null)
            {
                return HttpNotFound();
            }
            return View(discount);
        }

        // GET: Discount/Create
        public ActionResult _Create()
        {
            ViewBag.Flight_id = new SelectList(db.Flight, "Flight_id", "Flight_id");
            return PartialView("_Create");
        }

        // POST: Discount/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _Create([Bind(Include = "Discount_id,Flight_id,Discount1")] Discount discount)
        {
            if (ModelState.IsValid)
            {
                db.Discount.Add(discount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Flight_id = new SelectList(db.Flight, "Flight_id", "Flight_id", discount.Flight_id);
            return RedirectToAction("Index");
        }

        // GET: Discount/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discount discount = db.Discount.Find(id);
            if (discount == null)
            {
                return HttpNotFound();
            }
            ViewBag.Flight_id = new SelectList(db.Flight, "Flight_id", "Flight_id", discount.Flight_id);
            return View(discount);
        }

        // POST: Discount/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Discount_id,Flight_id,Discount1")] Discount discount)
        {
            if (ModelState.IsValid)
            {
                db.Entry(discount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Flight_id = new SelectList(db.Flight, "Flight_id", "Flight_id", discount.Flight_id);
            return View(discount);
        }

        // GET: Discount/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discount discount = db.Discount.Find(id);
            if (discount == null)
            {
                return HttpNotFound();
            }
            return View(discount);
        }

        // POST: Discount/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Discount discount = db.Discount.Find(id);
            db.Discount.Remove(discount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AirlinesReservation/Views/Discounts/Delete.cshtml
@model AirlinesReservation.Models.Discount

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Discount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Discount1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight.Flight_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.Flight_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AirlinesReservation/Views/Discounts/Edit.cshtml
@model AirlinesReservation.Models.Discount

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}

<div class="container-fluid">
    <div class="row page-titles">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">Manage Account<a href="/Admin/Index"></a></li>
            <li class="breadcrumb-item"><a href="/Emloyees/Index">Account</a></li>
            <li class="breadcrumb-item active" aria-current="page">Update Account</li>
        </ol>
    </div>
    <div class="row">
        <div class="col-12 h-75">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="container-fluid">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Discount</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Discount_id)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Flight_id, "Flight_id", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Flight_id", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Flight_id, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Discount1, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Discount1, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Discount1, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AirlinesReservation/Views/Discounts/Index.cshtml
@model IEnumerable<AirlinesReservation.Models.Discount>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}

@Html.Raw(TempData["mes"])
<div class="container-fluid">
    <div class="row page-titles">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="~/Flights/index">Admin</a></li>
            <li class="breadcrumb-item"><a href="">Manage Emloyee</a></li>
        </ol>
    </div>
    <div class="card-header d-flex justify-content-between">
        <div> <h4 class="card-title">Manage Discount</h4></div>>
        <button type="button" class="btn btn-rounded btn-success pull-right" data-bs-toggle="modal" data-bs-target=".dicount">
            <span class="btn-icon-start text-info">
                <i class="fa fa-plus color-info"></i>
            </span>Add
        </button>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example3" class="display" style="min-width: 845px">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Discount_id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Discount1)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Flight.Flight_id)
                                </th>
                                <th></th>
                            </tr>
                            
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Discount_id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Discount1)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Flight.Flight_id)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Discount_id }, new { @class = "btn btn-primary shadow btn-xs sharp me-1 fas fa-pencil-alt" })
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Discount_id }, new { @class = "btn btn-primary shadow btn-xs sharp me-1 fa fa-trash" })
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

AirlinesReservation/Views/Discounts/_Create.cshtml
@model AirlinesReservation.Models.Discount


<div class="modal fade dicount" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create Discount</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal">
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("_Create", "Discounts", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Discount_id, htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.EditorFor(model => model.Discount_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Discount_id, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Flight_id, "Flight_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("Flight_id", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Flight_id, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Discount1, htmlAttributes: new { @class = "control-label col-md-2" })

                            @Html.EditorFor(model => model.Discount1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Discount1, "", new { @class = "text-danger" })
                        </div>


                        <div class="mb-3" style="margin-top:1.5em;">
                            <input type="submit" value="Create" class="btn btn-primary btn-block" />
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>